site_name: Ptah
repo_url: https://github.com/dkmiller/ptah
repo_name: dkmiller/ptah

nav:
  - Home: index.md
  - Guides:
    - Installation: guides/install.md
  - Tutorials:
    - First project: tutorials/first-project.md
  - Reference:
    - ptah.yml: reference/project.md
    - CLI: reference/cli.md
    - Dependencies: reference/dependencies.md
  - Explanation:
    - FAQ: explanation/faq.md
    - Concepts: explanation/concepts.md

theme:
  name: material
  features:
    - content.code.copy

strict: true

markdown_extensions:
  - admonition
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
