site_name: Ptah
nav:
  - Home: index.md
  - Guides:
    - Installation: guides/install.md
  - Tutorials:
    - First project: tutorials/first-project.md
  - Reference:
    - ptah.yml: reference/config.md
  - FAQ: faq.md

theme:
  name: material
