[project]
name = "ptah-cli"
readme = "README.md"
version = "0.0.3"
authors = [
    { name = "Dan Miller", email = "daniel.keegan.miller@gmail.com" }
]
requires-python = ">=3.11,<3.13"
dependencies = [
    "injector>=0.21.0",
    "omegaconf>=2.3.0",
    "typer>=0.12.3",
]

[project.optional-dependencies]
dev = [
    "build==1.2.1",
    "isort==5.11.5",
    "pytest==7.4.3",
    "ruff==0.6.3",
]
doc = [
    "mkdocs==1.6.1",
    "mkdocs-material==9.5.34",
]

[project.scripts]
ptah = "ptah.cli:app"

[tool.isort]
known_local_folder = ["ptah"]
profile = "black"

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]

[tool.setuptools.package-data]
ptah = ["**/*.py"]
