name: python

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  python:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        python-version:
        - 3.9
        - 3.12

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[dev]

    - run: ruff check .

    - run: ruff format --check .

    - run: python -m build --wheel

    - uses: haya14busa/action-cond@v1
      id: singleton
      with:
        cond: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12' && github.actor != 'dependabot[bot]' }}
        if_true: true

    - uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/
      if: ${{ steps.singleton.outputs.value }}

  pypi-publish:
    # TODO: only run this on main.
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ptah-cli
    permissions:
        id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
